name       : openpaperwork-core
version    : 2.1.0
release    : 2
source     :
    - https://pypi.io/packages/source/o/openpaperwork-core/openpaperwork-core-2.1.0.tar.gz : 835915de918b6b341862f089b4238bcd2cdb8721f172cd7a1d478e8b96fc8439
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : Core part of Paperwork. It manages plugins.
description: |
    Paperwork is a GUI to make papers searchable. This is the core part of Paperwork.
networking : yes
builddeps  :
    - python-distro
    - python-psutil
rundeps    :
    - python-distro
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
